version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: nutrient-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: nutrient_db
    volumes:
      - mongodb_data:/data/db
      - ./data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - nutrient-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nutrient-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/nutrient_db?authSource=admin
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USDA_API_KEY=${USDA_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - ./ml-models:/app/ml-models
    networks:
      - nutrient-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nutrient-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - nutrient-network

volumes:
  mongodb_data:

networks:
  nutrient-network:
    driver: bridge
